### ISSUE TITLE
Tracing tools ?

### ISSUE THREAD

**Issue by ghost** [pion/website#29]
What tools are there to help trace the connections inside and outside chrome ?

**Comment by gedw99** [comment]
hey @gedw99 i asked because i am trying to get pions working with Web browser and desktop apps ( flutter).  Its better if you put the tooling descriptions somewhere in github for now JUST to get going ?
Desperate. 

Also maybe we should build something also i suspect, because you need often golang tools that are cross platform.

**Comment by maxhawkins** [comment]
I started work on a pcap writer here: https://github.com/pions/webrtc/pull/521
